- hosts: root-login

  vars:
    user: ichiwa
    password: $6$ichiwa$eMivSHkmuyIlHQwusbvtIjtW1DhcEE2qfDeEwKIzRiQc00IheqUfuSDGQkfe3/Ee8ctojT.bI58.nfxJPztcT0
    authorized_keys_dir: "/home/{{ user }}/.ssh"
    authorized_keys_file: "authorized_keys"

  vars_prompt:
  - name: update_yum
    prompt: "Are you sure you want to update yum?"
    private: no
    default: n

  tasks:
    - name: update_yum_packages
      yum: name=* state=latest
      when: update_yum == "y"

    - name: add user
      user: name={{ user }}
            password={{ password }}
      changed_when: false

    - name: add user to wheel group
      shell: gpasswd -a ichiwa wheel
      ignore_errors: true
      changed_when: false

    - name: allow sudo without password
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'

    - name: change sshd_config settings
      # change RSAAuthentication to yes
      replace:
          dest: /etc/ssh/sshd_config
          regexp: '#RSAAuthentication[^\n]*'
          replace: 'RSAAuthentication yes'
      # change PubkeyAuthentication to yes
      replace:
          dest: /etc/ssh/sshd_config
          regexp: '#PubkeyAuthentication[^\n]*'
          replace: 'PubkeyAuthentication yes'
      # change AuthorizedKeysFile	.ssh/authorized_keys
      replace:
          dest: /etc/ssh/sshd_config
          regexp: '#AuthorizedKeysFile[^\n]*'
          replace: "AuthorizedKeysFile	{{ authorized_keys_dir }}/{{ authorized_keys_file }}"

    # restart sshd
    - name: systemctl restart sshd.service
      shell: systemctl restart sshd.service

    - name: make authorized_keys directory
      file:
        path: "{{ authorized_keys_dir }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: wait for authroized_keys_dir created
      wait_for:
        path: "{{ authorized_keys_dir }}"
        state: started

    - name: create authorized_keys file
      file:
        path: "{{ authorized_keys_dir }}/{{ authorized_keys_file }}"
        state: touch
        owner: "{{ user }}"
        group: "{{ user }}"
