---
- name: Copy the NGINX repository definition
  copy: src=nginx.repo dest=/etc/yum.repos.d/

- name: Create the GPG key for NGINX
  copy: src=RPM-GPG-KEY-NGINX dest=/etc/pki/rpm-gpg

- name: Install nginx
  yum: name=nginx state=present

- name: insert firewalld rule for nginx
  firewalld: port=80/tcp permanent=true state=enabled immediate=yes

- name: Copy nginx Configuration
  template: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: Copy nginx configuration for wordpress
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
