---
- name: Setup Server
  hosts: cocoa
  remote_user: root

  vars_prompt:
  - name: updateYum
    prompt: "Are you sure you want to update yum?"
    private: yes
    default: n

  roles:
    - common
    - create-user
    - nginx
    - nodejs
    - mariadb
    - npm
    # - mongod
    # - elasticsearch
    # - mongod-plugins # full-text search for japanese
    - ghost
