---
- name: Install npm
  yum: name=npm state=latest enablerepo=epel

# Install
- name: Install node packages
  npm: name={{ item }} global=yes
  with_items:
    - elasticdump
    - n

# install node.js by n command
- name: Install stable node.js
  shell: n stable
