---
# This playbook will install MariaDB and create db user and give permissions.
# - name: Remove default fuc○ing MariaDB !!!!
#   yum: name={{ item }} state=absent
#   with_items:
#     - mariadb
#     - mariadb-libs

- name: Install MariaDB package
  yum: name={{ item }} state=installed
  with_items:
   - mariadb-server
   - MySQL-python
   - libselinux-python
   - libsemanage-python

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes
  ignore_errors: true

- name: Create Mysql configuration file
  copy: src=my.cnf dest=/etc/my.cnf
  notify:
  - restart mariadb

- name: Create MariaDB log file
  file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775

- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes

- name: insert firewalld rule
  firewalld: port=3306/tcp permanent=true state=enabled immediate=yes

################
# For security #
################

# Removes anonymous user account for localhost
- name: Removes anonymous user account for localhost
  mysql_user: name='' host=localhost state=absent
  ignore_errors: true

# Change root password
- name: Change root password
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
  with_items:
    - 127.0.0.1
    - localhost
  ignore_errors: true

# Create Ghost user in mysql(mariadb)
- name: Create Ghost user in mysql(mariadb)
  mysql_user: login_user=root login_password={{ mysql_root_password }} name=ghost password="{{ mysql_ghost_password }}" priv=*.*:ALL state=present

# Create Ghost database
- name: Create Ghost database
  shell: "mysqladmin -uroot -p{{ mysql_ghost_password }} create ghost"
  ignore_errors: true

# Create peacem database
- name: Create peacem database
  shell: "mysqladmin -uroot -p{{ mysql_ghost_password }} create peacem"
  ignore_errors: true
