---
# Create share directory
- name: Create share directory
  file:
    path: "{{ www_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755

# Install pm2
- name: Install pm2
  npm: name=pm2 global=yes

# Download ghost realesed version
- name: Download ghost realesed version
  get_url: url="{{ ghost_download_url }}" dest="{{ www_dir }}/ghost.zip"
  become: true
  become_user: "{{ user }}"

- name: wait for downloading ghost.zip
  wait_for:
    path: "{{ www_dir }}/ghost.zip"
    state: started

# Unzip ghost
- name: Unzip ghost
  command: unzip -n "{{ www_dir }}/ghost.zip" -d "{{ www_dir }}/ghost"
  become: true
  become_user: "{{ user }}"
  args:
    chdir: "{{ www_dir }}"

# Install ghost
- name: Install ghost
  shell: GHOST_NODE_VERSION_CHECK=false npm install --production
  become: true
  become_user: "{{ user }}"
  ignore_errors: yes
  args:
    chdir: "{{ www_dir }}/ghost"

# Copy ghost configuration
- name: Copy ghost configuration
  copy: src=config.js dest="{{ www_dir }}/ghost/config.js" owner="{{ user }}" group="{{ user }}"

# Copy pm2 script
- name: Copy pm2 configuration
  copy: src=ghost.json dest="{{ www_dir }}/ghost/ghost.json" owner="{{ user }}" group="{{ user }}"
