- name: Update yum packages
  yum: name=* state=latest
  when: updateYum == "y"

- name: install required packages
  yum: name="{{ item }}" state=installed
  with_items:
    - vim
    - wget
    - git
    - telnet
