- name: Update yum packages
  yum: name=* state=latest exclude=kernel*
  when: updateYum == "y"

- name: install required packages
  yum: name="{{ item }}" state=installed
  with_items:
    - vim
    - wget
    - git
    - telnet
    - unzip
    - java-1.7.0-openjdk
    - redis

- name: restart redis
  service: name=redis state=restarted

