---
- name: add user
  user: name={{ user }} password={{ password }}
  changed_when: false

- name: add user to wheel group
  shell: gpasswd -a ichiwa wheel
  ignore_errors: true
  changed_when: false

- name: allow sudo without password
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: change sshd_config settings
  # change RSAAuthentication to yes
  replace:
    dest: /etc/ssh/sshd_config
    regexp: '#RSAAuthentication[^\n]*'
    replace: 'RSAAuthentication yes'
  # change PubkeyAuthentication to yes
  replace:
    dest: /etc/ssh/sshd_config
    regexp: '#PubkeyAuthentication[^\n]*'
    replace: 'PubkeyAuthentication yes'
  # change AuthorizedKeysFile	.ssh/authorized_keys
  replace:
    dest: /etc/ssh/sshd_config
    regexp: '#AuthorizedKeysFile[^\n]*'
    replace: "AuthorizedKeysFile	{{ authorized_keys_dir }}/{{ authorized_keys_file }}"

# restart sshd
- name: systemctl restart sshd.service
  shell: systemctl restart sshd.service

- name: make authorized_keys directory
  file:
    path: "{{ authorized_keys_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: wait for authroized_keys_dir created
  wait_for:
    path: "{{ authorized_keys_dir }}"
    state: started

- name: copy id_rsa.pub to authorized_keys file
  copy:
    src: ~/.ssh/id_rsa.pub
    dest: "{{ authorized_keys_dir }}/{{ authorized_keys_file }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0600
